

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdatabase?createDatabaseIfNotExist=true
    username: root
    password: arul

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
        ddl-auto: update
    properties:
        hibernate:
            globally_quoted_identifiers: false  # Not generally needed for MySQL
  servlet:
    multipart:
        enabled: true
        max-file-size: 1000MB
        max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
        request-timeout: 3600000
server:
    port: 8085
    error:
        path: /user/error
        whitelabel:
            enabled: false
